Proyectos.NET/ExamenIsmaelBernad/ExamenIsmaelBernad/Components/ProvinciasComunidadViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using ExamenIsmaelBernad.Services;
using ExamenIsmaelBernad.Modelos;

namespace ExamenIsmaelBernad.Components
{
    public class ProvinciasComunidadViewComponent : ViewComponent
    {
        public IProvinciaRepositorio ProvinciaRepositorio { get; }

        public ProvinciasComunidadViewComponent(IProvinciaRepositorio provinciaRepositorio)
        {
            ProvinciaRepositorio = provinciaRepositorio;
        }

        public IViewComponentResult Invoke(Comunidad? comunidad = null) //puede recibir un objto comunidad o no, en ese caso será null
        {
            var resultado = ProvinciaRepositorio.ComunidadCuantosProvincia(comunidad);
            return View(resultado);
        }
    }
}

Proyectos.NET/ExamenIsmaelBernad/ExamenIsmaelBernad/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ExamenIsmaelBernad.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Proyectos.NET/ExamenIsmaelBernad/ExamenIsmaelBernad/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ExamenIsmaelBernad.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Proyectos.NET/ExamenIsmaelBernad/ExamenIsmaelBernad/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ExamenIsmaelBernad.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Proyectos.NET/ExamenIsmaelBernad/ExamenIsmaelBernad/Pages/Provincias/ProvinciasPorComunidad.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ExamenIsmaelBernad.Pages.Provincias
{
    public class ProvinciasPorComunidadModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Proyectos.NET/ExamenIsmaelBernad/ExamenIsmaelBernad/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Proyectos.NET/ExamenIsmaelBernad/ExamenIsmaelBernad/Pages/Provincias/FormularioComunidad.cshtml
@page
@using ExamenIsmaelBernad.Modelos;
@model ExamenIsmaelBernad.Pages.Provincias.FormularioComunidadModel
@{
}
<form method="post" class="mt-3" enctype="multipart/form-data">
    <div class="form-group row">
        <div class="col-sm-10">
            <select class="form-select mb-3" asp-items="Html.GetEnumSelectList<Comunidad>()">
                <!--Añadido el using RazorPages.Modelos en _ViewImports.cshtml-->
                <option value="Selecciona uno">Selecciona una Comunidad</option>
            </select>
        </div>
        <div class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Sacar Provincias</button>
            </div>
        </div>
    </div>
</form>


<div class="card-group">
    <h1>Provincias de esa comunidad: </h1>
    <br />
    @if (Model.Provincias != null && Model.Provincias.Any())
    {
        @foreach (var provincia in Model.Provincias)
        {
            <div class="card m-3 border" style="min-width: 18rem; max-width:30%">
                <div class="card-header">
                    <p>CodProvincia: @provincia.codProvincia</p>
                    <p>NomProvincia:  @provincia.nomProvincia</p>
                    <p>Superficie: @provincia.superficie</p>
                    <p>Numero habitantes:  @provincia.nomProvincia</p>
                    <p>CodComunidad: @provincia.codComunidad</p>
                </div>
            </div>
        }
    }
    else
    {
        <p>No has seleccionado una comunidad.</p>
    }
</div>

Proyectos.NET/ExamenIsmaelBernad/ExamenIsmaelBernad/Pages/Provincias/ListaProvincias.cshtml
@page
@model ExamenIsmaelBernad.Pages.Provincias.ListaProvinciasModel
@{
}
<h1>Provincias</h1>


<div class="col-sm-8">
    @await Component.InvokeAsync("ProvinciasComunidad")
</div>


<div class="card-group">
    @foreach(var provincia in Model.Provincias)
    {
        <div class="card m-3 border" style="min-width: 18rem; max-width:30%">
            <div class="card-header">
                <p>CodProvincia: @provincia.codProvincia</p>
                <p>NomProvincia:  @provincia.nomProvincia</p>
                <p>Superficie: @provincia.superficie</p>
                <p>Numero habitantes:  @provincia.nomProvincia</p>
                <p>CodComunidad: @provincia.codComunidad</p>
                
            </div>
        </div>
    }
</div>

Proyectos.NET/ExamenIsmaelBernad/ExamenIsmaelBernad/Pages/Provincias/ProvinciasPorComunidad.cshtml
@page
@model ExamenIsmaelBernad.Pages.Provincias.ProvinciasPorComunidadModel
@{
}